### ISSUE TITLE
Draft project are visible to the public

### ISSUE THREAD

**Issue by maredudd** [meigwilym/cytarse#66]
**Steps to reproduce**

1. Log out
2. Go to the URL of a draft project

**Expected result**

I'm not sure what the expected behaviour is here.  The project is visible to everyone.  I wouldn't want my project to be visible to everyone, but if a few people are setting up a project then it's good that they can see a draft of it.  As long as the URL can't be found easily then it isn't a big problem perhaps.  But, if you now follow the following steps you'll see that it's quite easy to find these projects:

1. Click on the name of the project creator where it says something like "A project in Art & Design by **Twm**".
2. Click on 'Created Projects'

Now, it's possible to see a list of the user's draft projects.

**Comment by MattHall** [comment]
@nwdls What's the plan for this one? Hide all drafts or is this expected behaviour? Note that this means that projects that have not been reviewed / approved are visible.

**Comment by nwdls** [comment]
@MattHall  1. We don't want users drafts visible on their profile page. Only live and ended projects
2. I would say that we should keep the draft projects hidden full stop. Kickstarter has ways that peopl can collaborate, but what I think that maybe they can just share a login if needs be. Probably best to have this as a feature to add in at a later date if requested rather than something that has the possibility of creating problems. 

So, can you make all drafts  hidden please? Thanks

**Comment by nwdls** [comment]
Hmmm. I've changed my mind about this. @MattHall how much work is it to allow links to draft projects to be visible if the user decides to share the link (but not visible on their profile or anywhere else on the site)? 

Sorry to change my mind, it's just that it makes sense for users to be able to share.

**Comment by MattHall** [comment]
Actually, going to the URL of a draft project works already - draft projects are just not listed on other pages (index, profile, etc)

**Comment by nwdls** [comment]
Ok! Great
